@startuml

title DDD + OAuth2 + JWT + Redis + K8s Flow

actor User
participant "deploy_k8s.bat" as DeployScript
participant Docker
participant Kubectl
participant "K8s Cluster" as K8s
participant "MyApp Pod" as MyApp
participant "Redis Pod" as Redis

== 배포(Deployment) ==
User -> DeployScript: Run batch (deploy_k8s.bat)
DeployScript -> Docker: Build Image (docker build)
DeployScript -> Kubectl: Apply YAMLs (kubectl apply)
Kubectl -> K8s: Create MyApp Pod and Redis Pod
K8s -> MyApp: Pod Starts
K8s -> Redis: Pod Starts


@enduml
