services:
  redis-node1:
    image: redis:latest
    container_name: redis-node1
    ports:
      - "7001:6379"
    volumes:
      - ./node1:/usr/local/etc/redis
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--appendonly", "yes"]
    networks:
      - redis-cluster-net

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    ports:
      - "7002:6379"
    volumes:
      - ./node2:/usr/local/etc/redis
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--appendonly", "yes"]
    networks:
      - redis-cluster-net

  redis-node3:
    image: redis:latest
    container_name: redis-node3
    ports:
      - "7003:6379"
    volumes:
      - ./node3:/usr/local/etc/redis
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--appendonly", "yes"]
    networks:
      - redis-cluster-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    driver: bridge
