global:
  redis:
    password: redis-password # Redis 비밀번호 설정

cluster:
  nodes: 6  # 총 노드 수 (마스터 + 슬레이브)
auth:
  enabled: true
  password: "redis-password"
persistence:
  enabled: true  # 데이터 영구 저장
  size: 1Gi   # 볼륨 크기 설정
  storageClass: "" # 스토리지 클래스 지정 (기본값 사용 시 빈 문자열)

#networkPolicy:
#  enabled: false # 네트워크 정책 비활성화
#
#metrics:
#  enabled: true       # Prometheus 메트릭 활성화
#  serviceMonitor:
#    enabled: false    # ServiceMonitor 비활성화
