# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-demo-app
  template:
    metadata:
      labels:
        app: redis-demo-app
    spec:
      containers:
        - name: redis-demo-app
          image: redis-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_REDIS_CLUSTER_PASSWORD
              value: "CkKGUP39YP"  # 현재 Redis 비밀번호
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              value: "my-redis-redis-cluster-0.my-redis-redis-cluster-headless:6379,my-redis-redis-cluster-1.my-redis-redis-cluster-headless:6379,my-redis-redis-cluster-2.my-redis-redis-cluster-headless:6379,my-redis-redis-cluster-3.my-redis-redis-cluster-headless:6379,my-redis-redis-cluster-4.my-redis-redis-cluster-headless:6379,my-redis-redis-cluster-5.my-redis-redis-cluster-headless:6379"
            - name: SPRING_DATA_REDIS_CLUSTER_MAX_REDIRECTS
              value: "3"