# iniyo/mytestauthserver

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosignapp
  labels:
    app: demosignapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demosignapp
  template:
    metadata:
      labels:
        app: demosignapp
    spec:
      containers:
        - name: demosignapp
          image: iniyo/mytestauthserver:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kakao-secret
                  key: client-id
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kakao-secret
                  key: client-secret
          # etc... DB, JWT key 등도 Secret으로 관리 가능
