# spring-boot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: redis-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: iniyo/mytestauthserver:latest # 사용자 Docker 이미지
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-cluster-master.redis-cluster.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "your_password"
