# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-demo-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: redis-demo-app