# spring-boot-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: redis-cluster
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  persistence:
    enabled: true
    storageClass: "hostpath"
    size: 1Gi
  type: LoadBalancer
