apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: demosignapp
spec:
  selector:
    app: demosignapp
  ports:
    - port: 80
      targetPort: 8080
      name: http
      nodePort: 30080
  type: NodePort # LoadBalancer           # 외부에서 접근 가능하도록 설정
